# Generated by Django 4.2.4 on 2023-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.signfix.com.au/wp-content/uploads/2017/09/placeholder-600x400.png', max_length=500),
        ),
    ]
